name: Auto publish data snapshot

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes; adjust as you like
  workflow_dispatch:         # still lets you run it manually if needed

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure deps
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          python3 -V

      - name: Package CSVs
        run: |
          mkdir -p data/packages
          (cd data && zip -r ../data/packages/data_csvs.zip . -i "**/*.csv" || true)
          ls -lah data/packages || true

      - name: Build manifest.json and snapshot (markdown)
        run: |
          python3 - << 'PY'
          import csv, json, glob, hashlib
          from pathlib import Path
          pkg = Path("data/packages"); pkg.mkdir(parents=True, exist_ok=True)
          rep = Path("reports");       rep.mkdir(parents=True, exist_ok=True)
          manifest = {"files": []}
          md = ["# Data Snapshot", ""]
          for path in sorted(glob.glob("data/**/*.csv", recursive=True)):
            h = hashlib.sha256()
            with open(path, "rb") as f:
              for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
            sha = h.hexdigest()
            headers = []; samples = []; rows = 0
            with open(path, newline="", encoding="utf-8") as f:
              rdr = csv.reader(f)
              headers = next(rdr, [])
              for r in rdr:
                rows += 1
                if len(samples) < 5: samples.append(r)
            manifest["files"].append({
              "path": path, "sha256": sha, "headers": headers,
              "row_count": rows, "sample_rows": samples
            })
            # append to markdown snapshot
            md.append(f"## `{path}`"); md.append("")
            md.append(f"- Rows: **{rows}**")
            md.append(f"- SHA256: `{sha}`"); md.append("")
            md.append("**Headers**"); md.append("")
            md.append("`" + ", ".join(headers) + "`"); md.append("")
            md.append("**First 5 rows**"); md.append("")
            md.append("| " + " | ".join(headers) + " |")
            md.append("|" + "|".join(["---"]*len(headers)) + "|")
            for r in samples:
              md.append("| " + " | ".join(r) + " |")
            md.append("")
          (pkg/"manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
          (rep/"DATA_SNAPSHOT.md").write_text("\n".join(md), encoding="utf-8")
          print("Wrote", pkg/"manifest.json", "and", rep/"DATA_SNAPSHOT.md")
          PY

      - name: Commit to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-publish data snapshot"
          commit_user_name: data-bot
          commit_user_email: actions@github.com
          branch: main
          file_pattern: |
            data/packages/data_csvs.zip
            data/packages/manifest.json
            reports/DATA_SNAPSHOT.md