name: Publish data CSVs

on:
  push:
    branches: [ main, master ]
    paths:
      - "data/**/*.csv"
      - ".github/workflows/publish-data-artifacts.yml"
  workflow_dispatch:

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure zip is available
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Package CSVs
        run: |
          mkdir -p artifacts
          # zip all CSVs under data/ (recursive), keep paths
          (cd data && zip -r ../artifacts/data_csvs.zip . -i "**/*.csv")
          ls -lah artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-csvs
          path: artifacts/data_csvs.zip
          if-no-files-found: error
          retention-days: 14
